Repository sumcumo/vue-datepicker, pull requests merged in 2020-10, with the labels that each got.

#35 Change formatDate replacements with a single replace function call
  src/utils/DateUtils.js
  test/unit/specs/DateUtils.spec.js
Labels: bug

#38 Add year range picker prop
  docs/.vuepress/components/Demo.vue
  docs/guide/Props/README.md
  example/Demo.vue
  src/components/Datepicker.vue
  src/components/PickerYear.vue
  test/unit/specs/PickerYear/pickerYear.spec.js
Labels: enhancement

#37 Add prop to append calendar to body
  docs/.vuepress/components/style.css
  docs/guide/Props/README.md
  docs/guide/README.md
  example/Demo.vue
  jest.conf.js
  jest.config.js
  package.json
  src/components/Datepicker.vue
  src/components/Popup.vue
  src/utils/calendarSlots.js
  src/utils/dom.js
  test/unit/jest.conf.js
  test/unit/specs/Datepicker/Datepicker.spec.js
  test/unit/specs/Datepicker/setPickerPosition.spec.js
Labels: enhancement

#43 [Docs] Use number modifier to typecast as Number
  docs/.vuepress/components/Demo.vue
  example/Demo.vue
Labels: bug, documentation

#41 Add prop to determine first-day-of-week
  docs/.vuepress/components/Demo.vue
  docs/guide/Props/README.md
  example/Demo.vue
  src/components/Datepicker.vue
  src/components/PickerDay.vue
  src/components/PickerHeader.vue
  src/components/PickerMonth.vue
  src/components/PickerYear.vue
  src/locale/Language.js
  src/utils/DateUtils.js
  test/unit/specs/DateUtils.spec.js
  test/unit/specs/PickerDay/firstDayOfWeek.spec.js
  test/unit/specs/PickerDay/mondayFirst.spec.js
Labels: enhancement

#44 Fix typeable calendar input not being formatted on blur
  docs/.vuepress/components/Demo.vue
  src/components/DateInput.vue
  test/unit/specs/DateInput/typedDates.spec.js
Labels: enhancement

#45 Use kebab case for props on demo pages
  docs/.vuepress/components/Demo.vue
Labels: enhancement

#46 Replace blank days with dates from previous / next months
  docs/.vuepress/components/Demo.vue
  docs/guide/Props/README.md
  example/Demo.vue
  src/components/Datepicker.vue
  src/components/PickerDay.vue
  src/styles/style.scss
  src/utils/DateUtils.js
  test/unit/specs/PickerDay/firstDayOfWeek.spec.js
Labels: enhancement

#47 Style/tweak stylesheet colours
  docs/.vuepress/components/Demo.vue
  src/styles/style.scss
Labels: enhancement
